### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Voker57** [eqv/gdb-mi-parser#1]
Hello

Thank you for your project, it helped greatly in my own one.
Could you please specify a license so your code could be more easily reused?

**Comment by bbbrumley** [comment]
@eqv Gentle nudge -- any thoughts on a license? My team of academic researchers will soon release a FOSS tool where `gdb-mi-parser` is a dependency :)

**Comment by eqv** [comment]
fixed #2, let me know if MIT doesn't work for you for some reason.
